# Generated by Django 3.0.7 on 2021-03-05 03:10

import college.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0003_auto_20210225_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='review',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='admission',
            name='admit_card',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=college.models.Admission.admit_card),
        ),
        migrations.AlterField(
            model_name='admission',
            name='rank_card',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=college.models.Admission.rank_card),
        ),
        migrations.AlterField(
            model_name='question',
            name='exam_end_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 5, 8, 39, 59, 944295)),
        ),
        migrations.AlterField(
            model_name='question',
            name='exam_start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 5, 8, 39, 59, 944295)),
        ),
        migrations.AlterField(
            model_name='student',
            name='admit_card',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=college.models.Student.admit_card),
        ),
        migrations.AlterField(
            model_name='student',
            name='rank_card',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=college.models.Student.rank_card),
        ),
    ]
