# Generated by Django 3.0.7 on 2021-05-25 05:38

import college.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0007_auto_20210306_1127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='exam_done',
            new_name='exam_done_ca1',
        ),
        migrations.AddField(
            model_name='result',
            name='exam_done_ca2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='result',
            name='exam_done_ca3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='result',
            name='exam_done_ca4',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='admission',
            name='admit_card',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=college.models.Admission.admit_card),
        ),
        migrations.AlterField(
            model_name='admission',
            name='rank_card',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=college.models.Admission.rank_card),
        ),
        migrations.AlterField(
            model_name='question',
            name='exam_end_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 25, 11, 8, 2, 201012)),
        ),
        migrations.AlterField(
            model_name='question',
            name='exam_start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 25, 11, 8, 2, 201012)),
        ),
        migrations.AlterField(
            model_name='student',
            name='admit_card',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=college.models.Student.admit_card),
        ),
        migrations.AlterField(
            model_name='student',
            name='rank_card',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=college.models.Student.rank_card),
        ),
    ]
