# Generated by Django 3.0.7 on 2021-05-26 19:16

import college.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0011_auto_20210526_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='attendance_time',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='admission',
            name='admit_card',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=college.models.Admission.admit_card),
        ),
        migrations.AlterField(
            model_name='admission',
            name='rank_card',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=college.models.Admission.rank_card),
        ),
        migrations.AlterField(
            model_name='question',
            name='exam_end_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 27, 0, 46, 54, 342594)),
        ),
        migrations.AlterField(
            model_name='question',
            name='exam_start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 27, 0, 46, 54, 342594)),
        ),
        migrations.AlterField(
            model_name='student',
            name='admit_card',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=college.models.Student.admit_card),
        ),
        migrations.AlterField(
            model_name='student',
            name='rank_card',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=college.models.Student.rank_card),
        ),
    ]
